import express from 'express';
import { getTraceId, logEvent, withTrace } from '../../lib/observability.mjs';
import { createQueue } from './queue.js';

const app = express(); app.disable('x-powered-by'); app.use(express.json({ limit:'32kb' }));
const queue = createQueue({ maxQueueDepth:process.env.MAX_QUEUE_DEPTH, maxInFlight:process.env.MAX_IN_FLIGHT, maxAttempts:process.env.MAX_JOB_ATTEMPTS, leaseSeconds:process.env.JOB_LEASE_SECONDS, completedTtlMs:process.env.COMPLETED_TTL_MS });
let shuttingDown = false;
app.use((req,res,next)=>{ const traceId=getTraceId(req); req.traceId=traceId; withTrace(res,traceId); res.setHeader('Cache-Control','no-store'); next(); });
app.get('/healthz',(_req,res)=>{ const s=queue.snapshot(); res.status(shuttingDown?503:200).json({ok:!shuttingDown,service:'worker',shutting_down:shuttingDown,queued:s.queued,in_flight:s.inFlight,dead_letter:s.deadLetter,capacity:s.capacity}); });
app.get('/readyz',(_req,res)=>shuttingDown?res.status(503).json({ready:false}):res.json({ready:true,service:'worker'}));
app.get('/metrics',(_req,res)=>{ const s=queue.snapshot(); const lines=['# HELP nowline_worker_queue_depth Number of queued jobs.','# TYPE nowline_worker_queue_depth gauge',`nowline_worker_queue_depth ${s.queued}`,'# HELP nowline_worker_in_flight Number of jobs currently claimed.','# TYPE nowline_worker_in_flight gauge',`nowline_worker_in_flight ${s.inFlight}`,'# HELP nowline_worker_dead_letter_depth Number of permanently failed jobs.','# TYPE nowline_worker_dead_letter_depth gauge',`nowline_worker_dead_letter_depth ${s.deadLetter}`,'# TYPE nowline_worker_jobs_total counter',...Object.entries(s.metrics).map(([name,value])=>`nowline_worker_jobs_total{state="${name}"} ${value}`)]; res.type('text/plain').send(lines.join('\n')+'\n'); });
app.post('/queue/jobs',(req,res)=>{ if(shuttingDown)return res.status(503).json({error:'worker_shutting_down',retryable:true}); const {type,payload={},idempotency_key:idempotencyKey}=req.body||{}; if(!type||typeof type!=='string'||type.length>128)return res.status(400).json({error:'job_type_required'}); if(typeof payload!=='object'||payload===null||Array.isArray(payload))return res.status(400).json({error:'job_payload_must_be_object'}); const result=queue.enqueue({idempotencyKey,type,payload,traceId:req.traceId,queuedAt:new Date().toISOString()}); if(!result.accepted&&result.reason==='queue_capacity_reached')return res.status(429).json({error:result.reason,retryable:true}); if(!result.accepted&&result.reason==='duplicate_job')return res.status(409).json({error:result.reason,idempotency_key:idempotencyKey}); if(!result.accepted)return res.status(400).json({error:result.reason}); logEvent('job_queued',{trace_id:req.traceId,job_type:type,idempotency_key:idempotencyKey,queue_depth:result.depth}); return res.status(202).json({accepted:true,job:result.job,depth:result.depth}); });
app.post('/queue/claim',(_req,res)=>{ if(shuttingDown)return res.status(503).json({error:'worker_shutting_down'}); const job=queue.claim(); if(!job)return res.status(204).end(); logEvent('job_claimed',{trace_id:job.traceId,job_type:job.type,idempotency_key:job.idempotencyKey,queue_depth:queue.snapshot().queued}); return res.json({job,depth:queue.snapshot().queued}); });
app.post('/queue/complete',(req,res)=>{ const {idempotency_key:idempotencyKey,ok=true}=req.body||{}; if(!idempotencyKey||typeof idempotencyKey!=='string')return res.status(400).json({error:'idempotency_key_required'}); const result=queue.complete(idempotencyKey,Boolean(ok)); if(!result.ok)return res.status(404).json({error:result.reason}); const eventName=result.state==='completed'?'job_completed':result.state==='dead_letter'?'job_dead_lettered':'job_retry_scheduled'; logEvent(eventName,{trace_id:result.job.traceId,idempotency_key:idempotencyKey,job_type:result.job.type,state:result.state,attempts:result.job.attempts}); return res.json({ok:true,idempotency_key:idempotencyKey,state:result.state,attempts:result.job.attempts}); });
app.get('/queue/jobs/:idempotencyKey',(req,res)=>{ const result=queue.get(req.params.idempotencyKey); if(!result)return res.status(404).json({error:'job_not_found'}); return res.json(result); });
const server=app.listen(Number(process.env.PORT||8080),()=>logEvent('worker_listening',{port:Number(process.env.PORT||8080)}));
function shutdown(signal){ if(shuttingDown)return; shuttingDown=true; logEvent('worker_shutdown_started',{signal,pending_jobs:queue.snapshot().queued+queue.snapshot().inFlight}); server.close(()=>process.exit(0)); setTimeout(()=>process.exit(1),Number(process.env.SHUTDOWN_TIMEOUT_MS||10000)).unref(); }
process.on('SIGTERM',()=>shutdown('SIGTERM')); process.on('SIGINT',()=>shutdown('SIGINT'));